// onsched-angular/src/app/app.component.ts
import { authConfig } from './auth.config';
import { Component, OnInit } from '@angular/core';
import { OAuthService, AuthConfig, JwksValidationHandler } from 'angular-oauth2-oidc';
import Swagger from 'swagger-client';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  public apiUrl = 'https://sandbox-api.onsched.com/swagger/v1/swagger.json';
  public customerData: any[];
  public tokenData: any[];

  constructor(private oauthService: OAuthService) {
    this.oauthService.configure(authConfig);
    this.oauthService.tokenValidationHandler = new JwksValidationHandler();
  }

  ngOnInit() {
    this.oauthService.loadDiscoveryDocumentAndTryLogin().then(_ => {
      if (!this.oauthService.hasValidIdToken() || !this.oauthService.hasValidAccessToken()) {
        this.oauthService.initImplicitFlow('some-state');
      } else {
        this.haveToken();
      }
    });

    this.noNeedToken();
  }

  login() {
    this.oauthService.initImplicitFlow('some-state');
  }

  logout() {
    this.oauthService.logOut();
  }

  noNeedToken() {
    Swagger(this.apiUrl).then((client) => {
      //      console.log(client);
      client.apis.Customers.ConsumerV1CustomersGet().then(res => {
        //        console.log(res.obj.data);
        this.customerData = res.obj.data;
      });
    });
    //      .catch((err) => {
    //        console.log(err);
    //      });
  }

  haveToken() {
    Swagger(this.apiUrl).then((client) => {
      console.log(client); // Log to see the api calls you can make
      const token = this.oauthService.getAccessToken();

      client.apis.HelloApi.HandshakeClaimsGet({}, {
        // Trick to add the header
        requestInterceptor: (req) => {
          req.headers.Authorization = 'Bearer ' + token;
          return req;
        }
      }).then(res => {
        // This is what the call returns
        this.tokenData = res.obj.data;
        console.log(this.tokenData);
      });
    });
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<div class="panel-body">
    <button class="btn btn-default" (click)="logout()">Logout</button>
</div>

Without Token
<ul>
  <li *ngFor="let key of customerData" text-center>{{key.name}}</li>
</ul>

With Token
<ul>
  <li *ngFor="let key of tokenData" text-center>{{key.name}}</li>
</ul>

// onsched-react-federated/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Swagger from 'swagger-client';
import Oidc from 'oidc-client';
import * as qs from 'query-string';

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      data: [],
      tokenData: [],
      apiUrl: 'http://sandbox-api.onsched.com/swagger/consumer/swagger.json',
      signinResponse: '',
      accessToken: qs.parse(window.location.hash).access_token
    };

  }

  componentWillMount() {
    Swagger(this.state.apiUrl).then((client) => {
      client.apis.Customers.ConsumerV1CustomersGet().then(res => {
        this.setState({data: res.data});
      });
    })
    .catch((err) => {
      console.log(err);
    });

    var settings = {
      authority: 'https://stage-identity.onsched.com',
      client_id: 'burlingtonjs',
      redirect_uri: window.location.href,
      post_logout_redirect_uri: window.location.href,
      response_type: 'token id_token',
      scope: 'openid OnSchedApi',
      acr_values: 'idp:Auth0', //Demo777@onsched.com 1234567
//      acr_values: 'idp:Google', //
      filterProtocolClaims: true,
      loadUserInfo: true
    };
    this.setState({client: new Oidc.OidcClient(settings)});
    console.log(this.state);
  }

  render() {
    const {data, tokenData} = this.state;
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Names from /consumer/v1/customers</h1>
        </header>
        <button onClick={_ => this.signin()}>Login</button>
        <button onClick={_ => this.haveToken()}>Use Token</button>
        <div className="App-intro">
          Access Token
          <p>{this.state.accessToken}</p>
        </div>
        <div className="App-intro">
          Without Token
          <ul>{data.map((item, index) => <li key={index}>{item.name}</li>)}</ul>
        </div>
        <div className="App-intro">
          With Token
          <ul>{Object.entries(tokenData).map((item, index) => <li key={index}>{item[0]}: {item[1]}</li>)}</ul>
        </div>
      </div>
    );
  }

  signin() {
    this.state.client.createSigninRequest({ state: { bar: 15 } }).then((req) => {
        console.log("signin request", req, "<a href='" + req.url + "'>go signin</a>");
        window.location = req.url;
    }).catch((err) => {
        console.log(err);
    });
  }

  haveToken() {
    if(this.state.accessToken) {

      const request = {
        url: 'https://sandbox-api.onsched.com/Handshake/hello/accessServiceinfo',
        requestInterceptor: (req) => {
          req.headers.Authorization = 'Bearer ' + this.state.accessToken;
          return req;
        }
      };

      Swagger.http(request).then((res) => {
        // This is what the call returns
        console.log(res);
        this.setState({tokenData: res.obj});
      }).catch((err) => {
        console.log(err);
      });

/*
      Swagger(this.state.apiUrl).then((client) => {
        client.apis.HelloApi.HandshakeClaimsGet({}, {
          // Trick to add the header
          requestInterceptor: (req) => {
            req.headers.Authorization = 'Bearer ' + this.state.accessToken;
            return req;
          }
        }).then(res => {
          // This is what the call returns
          this.setState({tokenData: res.obj});
        });
      })
      .catch((err) => {
        console.log(err);
      });
*/
    }
  }
}

export default App;
