// onsched-react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Swagger from 'swagger-client'

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {data: []};
  }

  componentWillMount() {
    let apiUrl= 'https://sandbox-api.onsched.com/swagger/v1/swagger.json';
    Swagger(apiUrl).then((client) => {
      client.apis.Customers.ConsumerV1CustomersGet().then(res => {
        this.setState({data: res.obj.data});
      });
    })
    .catch((err) => {
      console.log(err);
    });
  }

  render() {
    const {data} = this.state;
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Names from /consumer/v1/customers</h1>
        </header>
        <div className="App-intro">
          <ul>{data.map((item, index) => <li key={item.id}>{item.name}</li>)}</ul>
        </div>
      </div>
    );
  }
}

export default App;

// onsched-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import Swagger from 'swagger-client';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public apiUrl = 'https://sandbox-api.onsched.com/swagger/v1/swagger.json';
  public data: any[];

  constructor() {
    Swagger(this.apiUrl).then((client) => {
      client.apis.Customers.ConsumerV1CustomersGet().then(res => {
        console.log(res.obj.data);
        this.data = res.obj.data;
      });
    });
    //      .catch((err) => {
    //        console.log(err);
    //      });
  }

}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<ul>
  <li *ngFor="let key of data" text-center>{{key.name}}</li>
</ul>
